services:
  api:
    build:
      context : .
      dockerfile: "apps/api/dockerfile"
    ports:
      - "4000:4000"
      
    
  redis:
    image: "redis:7"
    ports:
      - "4379:4379"
    

  postgres:
    image: "postgres:17"
    ports:
      - "3000:3000"
    environments:
      DATABASE_URL: "postgresql://sketchly:secret@postgres:5432/sketchly"
volumes:
    